[package]
name = "vexination-indexer"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
csaf = { workspace = true }
tokio = { workspace = true, features = ["full"] }

vexination-index = { workspace = true }
trustification-event-bus = { workspace = true }
trustification-infrastructure = { workspace = true }
trustification-storage = { workspace = true }
trustification-index = { workspace = true }
trustification-indexer = { workspace = true }
