[package]
name = "v11y-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }
actix-web-httpauth = { workspace = true }
anyhow = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true, features = ["derive"] }
derive_more = { workspace = true }
log = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
utoipa = { workspace = true, features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }

trustification-api = { workspace = true }
trustification-auth = { workspace = true, features = ["actix", "swagger"] }
trustification-common = { workspace = true }
trustification-index = { workspace = true }
trustification-infrastructure = { workspace = true }
trustification-storage = { workspace = true }
v11y-index = { workspace = true }
v11y-model = { workspace = true }

[dev-dependencies]
env_logger = "0.11"
tempdir = "0.3.7"

