[package]
name = "vexination-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "Vexination REST API for fetching, publishing and searching VEX data"

[dependencies]
actix-web = { workspace = true }
actix-web-httpauth = { workspace = true }
anyhow = { workspace = true }
bytesize = { workspace = true }
clap = { workspace = true, features = ["derive"] }
csaf = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }

trustification-api = { workspace = true }
trustification-auth = { workspace = true, features = ["actix", "swagger"] }
trustification-index = { workspace = true }
trustification-infrastructure = { workspace = true }
trustification-storage = { workspace = true }
vexination-index = { path = "../index" }
vexination-model = { workspace = true }
