[package]
name = "v11y-model"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }
sikula = { workspace = true, default-features = false, features = ["time"] }
time = { workspace = true, features = ["serde", "formatting", "parsing"] }