[package]
name = "collectorist-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
trustification-auth = { path = "../../auth", features = ["swagger"] }
trustification-common = { path = "../../common" }
trustification-infrastructure = { path = "../../infrastructure" }
collectorist-client = { path = "../client" }
collector-client = { path = "../../collector/client" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
derive_more = "0.99"
futures = "0.3"
log = "0.4"
utoipa = { version = "4", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "6", features = ["actix-web"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.25"
tokio = { version = "1.0", features = ["full"] }
guac = { workspace = true }
sqlx = { version = "0.8.1", features = ["runtime-tokio", "sqlite", "chrono"] }
reqwest = "0.11.18"
chrono = "0.4.26"
humantime = "2"
humantime-serde = "1.1.1"
thiserror = "1.0.44"
actix-web-httpauth = "0.8.0"

[dev-dependencies]
serde_json = "1.0.68"
env_logger = "0.11"

#[build-dependencies]
#tonic-build = "0.9.2"
