[package]
name = "collectorist-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }
actix-web-httpauth = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
derive_more = { workspace = true }
futures = { workspace = true }
guac = { workspace = true }
humantime = { workspace = true }
humantime-serde = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "chrono"] }
thiserror = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }

collector-client = { workspace = true }
collectorist-client = { workspace = true }
trustification-auth = { workspace = true, features = ["swagger"] }
trustification-common = { workspace = true }
trustification-infrastructure = { workspace = true }

[dev-dependencies]
serde_json = "1.0.68"
env_logger = "0.11"

#[build-dependencies]
#tonic-build = "0.9.2"
