[package]
name = "trustification-common-walker"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "Common tools for walkers"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
time = { workspace = true, features = ["serde-well-known"] }
walker-common = { workspace = true }
walker-extras = { workspace = true }
tera = { workspace = true }
sequoia-openpgp = { workspace = true, default-features = false }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

# Enables a crypto backend for the tests:
[target.'cfg(not(windows))'.dev-dependencies]
sequoia-openpgp = { version = "1", default-features = false, features = ["crypto-nettle", "__implicit-crypto-backend-for-tests"]  }

# Enables a crypto backend for the docs.rs generation:
[package.metadata.docs.rs]
features = ["sequoia-openpgp/default"]
