[package]
name = "v11y-walker"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
cve = { workspace = true }
cvss = { workspace = true }
log = { workspace = true }
prometheus = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }
walkdir = { workspace = true }

collector-osv = { workspace = true }
trustification-infrastructure = { workspace = true }
trustification-storage = { workspace = true }
v11y-api = { workspace = true }
v11y-indexer = { workspace = true }
