[package]
name = "collector-snyk"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
guac = { workspace = true }
hide = { workspace = true }
log = { workspace = true }
packageurl = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
url-escape = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }

collector-client = { workspace = true }
trustification-auth = { workspace = true }
trustification-common = { workspace = true }
trustification-infrastructure = { workspace = true }
v11y-client = { workspace = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.11"
test-with = { version = "0.12", features = ["runtime"] }
libtest-with = { version = "0.7.0-1", features = ["net", "resource", "user", "executable"] }

[build-dependencies]

#schemafy_lib = "0.6.0"
#tonic-build = "0.9.2"
