[package]
name = "exhort-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { workspace = true }
actix-cors = { workspace = true }
guac = { workspace = true }
reqwest = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [ "raw_value" ] }
packageurl = { workspace = true }
regex = { workspace = true }
lenient_semver = { workspace = true, features = ["parse_partial"] }
semver = { workspace = true }

collectorist-client = { workspace = true }
exhort-model = { workspace = true }
v11y-client = { workspace = true }
trustification-common = { workspace = true }
trustification-infrastructure = { workspace = true }
trustification-auth = { workspace = true }


[dev-dependencies]
env_logger = "0.11"

[build-dependencies]
tonic-build = "0.11"
