[package]
name = "spog-model"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "The data model of the API"

[dependencies]
# required by ToSchema utopia
chrono = { workspace = true, default-features = false, features = ["serde"] }
csaf = { workspace = true, default-features = false }
cvss = { workspace = true }
packageurl = { workspace = true, features = ["serde"] }
schemars = { workspace = true, features = ["url"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
time = { workspace = true }
url = { workspace = true, features = ["serde"] }
urlencoding = { workspace = true }
utoipa = { workspace = true, features = ["url"] }

exhort-model = { workspace = true }
v11y-model = { workspace = true }
vexination-model = { workspace = true }


[dev-dependencies]
serde_json = "1"
anyhow = "1"