[package]
name = "reservoir-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = [ "derive" ] }
