[package]
name = "vexination-model"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "The data model of the API"

[dependencies]
serde = { workspace = true, features = ["derive"] }
sikula = { workspace = true, default-features = false, features = ["time"] }
time = { workspace = true, features = ["serde"] }
utoipa = { workspace = true }
# required by ToSchema utopia
serde_json = { workspace = true }
urlencoding = { workspace = true }
