[package]
name = "vexination-walker"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
csaf = { workspace = true }
csaf-walker = { workspace = true, default-features = false, features = ["crypto-openssl"] }
humantime = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
walker-common = { workspace = true }
walker-extras = { workspace = true }

trustification-auth = { workspace = true }
trustification-common-walker = { workspace = true }
trustification-infrastructure = { workspace = true }
