[package]
name = "vexination"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }

vexination-api = { workspace = true }
vexination-indexer = { workspace = true }
vexination-walker = { workspace = true }