[package]
name = "v11y-client"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

trustification-api = { workspace = true }
trustification-auth = { workspace = true }
trustification-infrastructure = { workspace = true }
v11y-model = { workspace = true }

[dev-dependencies]
tokio = "1"



