[package]
name = "spog-api"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
description = "An API server for trusted content"

[dependencies]
actix = { workspace = true }
actix-rt = { workspace = true }
actix-web = { workspace = true }
actix-web-extras = { workspace = true }
actix-web-httpauth = { workspace = true }
actix-ws = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
csaf = { workspace = true }
cve = { workspace = true }
cvss = { workspace = true }
futures = { workspace = true }
guac = { workspace = true }
hide = { workspace = true }
http = { workspace = true }
log = { workspace = true }
packageurl = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
spdx-rs = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "fs", "macros", "rt-multi-thread"] }
tracing = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
utoipa = { workspace = true, features = ["actix_extras", "yaml", "time"] }
utoipa-swagger-ui = { workspace = true, features = ["actix-web"] }
time = { workspace = true }

v11y-model = { workspace = true }
spog-model = { workspace = true }
vexination-model = { workspace = true }
bombastic-model = { workspace = true }
exhort-model = { workspace = true }
trustification-analytics = { workspace = true }
trustification-api = { workspace = true }
trustification-auth = { workspace = true, features = ["actix", "swagger"] }
collectorist-client = { workspace = true }
trustification-common = { workspace = true }
trustification-infrastructure = { workspace = true }
v11y-client = { workspace = true }
trustification-version = { workspace = true, features = ["actix-web"] }

[build-dependencies]
trustification-version = { path = "../../version", features = ["build"] }
