[package]
name = "spog-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

description = "An API server for trusted content"

[dependencies]
actix = "0.13"
actix-rt = "2"
actix-web = "4"
actix-web-extras = "0.1"
actix-web-httpauth = "0.8"
actix-ws = "*"
anyhow = "1"
async-trait = "0.1.73"
bytes = "1"
clap = { version = "4.0.29", features = ["derive"] }
csaf = "0.5"
cve = "0.3.1"
cvss = "2"
futures = "0.3"
guac = { workspace = true }
hide = "0.1.3"
http = "0.2"
log = "0.4"
packageurl = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11.16", features = ["stream"] }
serde = { version = "1.0.152" }
serde_json = "1.0.89"
serde_yaml = "0.9"
spdx-rs = "0.5.5"
thiserror = "1"
tokio = { version = "*", features = ["rt", "fs", "macros", "rt-multi-thread"] }
tracing = "0.1"
url = "2"
urlencoding = "2.1.2"
utoipa = { version = "4", features = ["actix_extras", "yaml", "time"] }
utoipa-swagger-ui = { version = "6", features = ["actix-web"] }
v11y-model = { path = "../../v11y/model" }

spog-model = { path = "../model" }
vexination-model = { path = "../../vexination/model" }
bombastic-model = { path = "../../bombastic/model" }

exhort-model = { path = "../../exhort/model" }

trustification-analytics = { path = "../../analytics" }
trustification-api = { path = "../../api" }
trustification-auth = { path = "../../auth", features = ["actix", "swagger"] }
collectorist-client = { path = "../../collectorist/client" }
trustification-common = { path = "../../common" }
trustification-infrastructure = { path = "../../infrastructure" }
v11y-client = { path = "../../v11y/client" }
trustification-version = { path = "../../version", features = ["actix-web"] }
time = "0.3.31"
sqlx = { version = "0.8.1", features = ["runtime-tokio", "sqlite", "chrono"] }

[build-dependencies]
trustification-version = { path = "../../version", features = ["build"] }
