[package]
name = "exhort-model"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
utoipa = { workspace = true }

v11y-model = { workspace = true }